### ISSUE TITLE
[Bug]: Can't call `resolvePeer` - `400 BOT_INVALID`.

### ISSUE THREAD

**Issue by LWJerri** [mtcute/mtcute#18]
Sometimes I receive error (see logs sections) without no reason. It can happens at random time.

## To Reproduce
1. Call `resolvePeer(899433974)`
2. With some chance you will receive error

p.s: 899433974 is @odesli_bot.

## Logs
![image](https://github.com/mtcute/mtcute/assets/50290430/3ace2946-4f93-4759-96dd-13d4c16394bf)

## Environment
OS: `Windows 11 (WSL 2 with Ubuntu 22.04)`.
Runtime: `Node.js v21.6.1`.
mtcute version: `^0.7.0`.

**Additional context**
No additional context.

**Comment by teidesu** [comment]
`resolvePeer` doesn't do any api calls when called with an ID, it just fetches the input peer from the local database. if the peer wasn't cached, it will return an input peer with `access_hash=0`, which for user accounts works *sometimes*

see https://mtcute.dev/guide/intro/faq.html#why-do-i-get-peer-id-invalid

a quick fix would be to replace the id with the username, which would make the library fetch the input peer if needed.
