### ISSUE TITLE
Move updates handling to `core`?

### ISSUE THREAD

**Issue by ghost** [mtcute/mtcute#2]
Currently updates handling is done in `updates.ts` file of `client` package, and `core` package only exposes a callback that is called whenever `tl.TypeUpdates` is received.

Correctly handling updates is pretty complex and should be done by a library, but I'm not entirely sure about moving updates handling to core since when using core, user might want to do something simple, or something very complex with custom storage schemes, etc., and in both cases updates handing isn't really needed. 

Also this would be a breaking change in the APIs.

**Comment by teidesu** [comment]
closing as update handling can be enabled for core client
