### ISSUE TITLE
Error reporting to non existing host

### ISSUE THREAD

**Issue by rumatoest** [mtcute/mtcute#72]
See:
packages/core/src/utils/error-reporting.ts

It sends errors to the non existing host rpc.pwrtelegram.xyz

BTW I have many security concerns about any error reporting to any external URL. Just do not turn it ON by default.

**Comment by teidesu** [comment]
it is disabled by default, and this service is hosted by danog who is closely related with telegram.

the API endpoint indeed seems to have changed to `report-rpc-error.madelineproto.xyz`, ill fix that

**Comment by teidesu** [comment]
fixed in https://github.com/mtcute/mtcute/commit/ecddcad0126405e73129d5d481e632ed81160fb0
