### ISSUE TITLE
Import gramjs session

### ISSUE THREAD

**Issue by Vance-ng-vn** [mtcute/mtcute#73]
**Is your feature request related to a problem? Please describe.**
I cant import session string from gramjd to mtcute

**Describe the solution you'd like**
Import session string from gramjs

**Comment by teidesu** [comment]
please provide a minimal repro with a sample session string. 
to avoid leaking sensitive info feel free to use the test phone numbers.

`@mtcute/convert` should already be able to convert gramjs sessions, and i don't see any changes in their string format since the initial implementation in `@mtcute/convert`

**Comment by Vance-ng-vn** [comment]
It seems to be an issue related to the socks5 proxy; after trying again with the http proxy, it worked :))

**Comment by Vance-ng-vn** [comment]
> please provide a minimal repro with a sample session string. to avoid leaking sensitive info feel free to use the test phone numbers.
> 
> `@mtcute/convert` should already be able to convert gramjs sessions, and i don't see any changes in their string format since the initial implementation in `@mtcute/convert`

Oh, it seems that the results are automatically saved in storage, and I mistook that for a successful login!

Is there a way to disable the storage feature?

And the login error with session gramjs looks like this:

```
file:///home/mx-vankaiser/Projects/Telegram%20Bot/not-pixel/node_modules/@mtcute/core/chunks/es/hecWgeql.js:60
    throw new Error(`Invalid session string (version = ${version})`);
          ^

Error: Invalid session string (version = 212)
    at readStringSession (file:///home/mx-vankaiser/Projects/Telegram%20Bot/not-pixel/node_modules/@mtcute/core/chunks/es/hecWgeql.js:60:11)
    at BaseTelegramClient.importSession (file:///home/mx-vankaiser/Projects/Telegram%20Bot/not-pixel/node_modules/@mtcute/core/client.js:219:48)
    at async Telegram._client (file:///home/mx-vankaiser/Projects/Telegram%20Bot/not-pixel/modules/telegram.js:33:21)
    at async Telegram.create (file:///home/mx-vankaiser/Projects/Telegram%20Bot/not-pixel/modules/telegram.js:15:24)
```

[tg.84927161120.session.zip](https://github.com/user-attachments/files/17281194/tg.84927161120.session.zip)

**Comment by Vance-ng-vn** [comment]
> once again, please provide your code you use to import the string session and the string session itself. from the traceback it seems to me that you aren't using `@mtcute/convert` at all, have you read [the docs](https://mtcute.dev/guide/advanced/session-convert.html#gramjs)?
> 
> > Is there a way to disable the storage feature?
> 
> why would you want that? you can use memory storage tho

Okay, sorry, I haven't read to the end of the docs yet :))
