### ISSUE TITLE
Uncaught (in promise) CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 64 6f @+0

### ISSUE THREAD

**Issue by tocha699** [mtcute/mtcute#79]
I am using tauri. When using @mtcute/web, an error occurred. I looked at the network request and found that 302 was returned when loading wasm. `http://localhost:1420/node_modules/.vite/deps/mtcute.wasm`

```
Uncaught (in promise) CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 64 6f @+0
```

I'm not sure where the problem is, here is my code

```
import { TelegramClient } from "@mtcute/web";
const client = new TelegramClient({
    apiId: 2040,
    apiHash: "b18441a1ff607e10a989891a5462e627",
})
```

**Comment by teidesu** [comment]
did you add it to `optimizeDeps.exclude`?

**Comment by tocha699** [comment]
Sorry, I don't, because I didn't see him in the documentation https://mtcute.dev/guide/#browser
